@php
$wa = preg_replace('/\D+/', '', (string) config('hotel.whatsapp'));
$whatsappLink = $wa !== '' ? 'https://wa.me/'.$wa : 'https://wa.me/';
$verifyUrl = \App\Services\ReservationDocument::verifyUrl($reservation);
@endphp
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Reserva #{{ $reservation->id }} confirmada - Casa Horizonte</title></head>
<body style="margin:0;padding:30px 12px;background:#f4f6f8;font-family:Arial,Helvetica,sans-serif;color:#333"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f6f8"><tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#fff;border-radius:16px;overflow:hidden">
<tr><td style="background:#1f2937;padding:32px 30px;text-align:center"><div style="font-size:28px;font-weight:bold;color:#fff;letter-spacing:1px">CASA HORIZONTE</div><div style="margin-top:8px;font-size:14px;color:#d1d5db">Hospedaje &nbsp;•&nbsp; Confort &nbsp;•&nbsp; Tranquilidad</div></td></tr>
<tr><td style="padding:35px 30px 20px;text-align:center"><div style="width:64px;height:64px;line-height:64px;background:#dcfce7;border-radius:50%;font-size:32px;color:#16a34a;margin:auto">✓</div><h1 style="margin:18px 0 8px;font-size:26px;color:#111827">¡Reserva confirmada!</h1><p style="margin:0;font-size:15px;color:#6b7280;line-height:1.6">Hola <strong>{{ $reservation->user->name }}</strong>, tu reserva en <strong>Casa Horizonte</strong> ha sido confirmada correctamente.</p></td></tr>
<tr><td style="padding:10px 30px 25px"><div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:12px;padding:24px"><h2 style="margin:0 0 18px;font-size:18px;color:#111827">🏨 Detalles de tu reserva</h2><p style="margin:0;padding:11px 0;border-bottom:1px solid #e5e7eb;color:#6b7280;font-size:14px">Habitación <strong style="float:right;color:#111827">{{ $reservation->room->room_number }} · {{ $reservation->room->type }}</strong></p><p style="margin:0;padding:11px 0;border-bottom:1px solid #e5e7eb;color:#6b7280;font-size:14px">📅 Fecha de entrada <strong style="float:right;color:#111827">{{ $reservation->check_in }}</strong></p><p style="margin:0;padding:11px 0;border-bottom:1px solid #e5e7eb;color:#6b7280;font-size:14px">📅 Fecha de salida <strong style="float:right;color:#111827">{{ $reservation->check_out }}</strong></p><p style="margin:0;padding:18px 0 5px;color:#111827;font-size:16px;font-weight:bold">Total <strong style="float:right;color:#16a34a;font-size:23px">${{ number_format((float) $reservation->total_price, 2) }}</strong></p></div></td></tr>
<tr><td style="padding:0 30px 25px"><div style="background:#eff6ff;border-left:4px solid #2563eb;padding:18px 20px;border-radius:8px"><p style="margin:0 0 8px;font-size:15px;color:#1e3a8a;font-weight:bold">🧳 Información importante</p><p style="margin:0;font-size:14px;color:#374151;line-height:1.7">Hemos registrado tu reserva correctamente. Te recomendamos guardar este correo y presentarlo al momento de tu llegada.</p></div></td></tr>
<tr><td style="padding:0 30px 25px"><table width="100%" cellpadding="0" cellspacing="0"><tr><td width="48%" valign="top" style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:10px;padding:18px"><div style="font-size:13px;color:#6b7280">🕐 CHECK-IN</div><div style="margin-top:7px;font-size:16px;font-weight:bold;color:#111827">Desde las 2:00 PM</div></td><td width="4%"></td><td width="48%" valign="top" style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:10px;padding:18px"><div style="font-size:13px;color:#6b7280">🕐 CHECK-OUT</div><div style="margin-top:7px;font-size:16px;font-weight:bold;color:#111827">Hasta las 12:00 PM</div></td></tr></table></td></tr>
<tr><td style="padding:0 30px 25px"><div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:12px;padding:22px;text-align:center"><h2 style="margin:0 0 8px;font-size:18px;color:#111827">¿Necesitas ayuda?</h2><p style="margin:0 0 18px;font-size:14px;color:#6b7280">Estamos disponibles para ayudarte con cualquier consulta.</p><a href="{{ $whatsappLink }}" style="display:inline-block;background:#25D366;color:#fff;text-decoration:none;font-size:14px;font-weight:bold;padding:12px 22px;border-radius:7px">💬 Contactar por WhatsApp</a><div style="margin-top:14px;font-size:13px;color:#6b7280">📞 {{ config('hotel.phone') }}</div><div style="margin-top:5px;font-size:13px;color:#6b7280">✉️ {{ config('hotel.email') }}</div></div></td></tr>
<tr><td style="padding:0 30px 25px"><div style="background:#fff7ed;border:1px solid #fed7aa;border-radius:10px;padding:18px 20px"><div style="font-size:15px;font-weight:bold;color:#9a3412">📍 ¿Cómo llegar?</div><p style="margin:7px 0 14px;font-size:14px;color:#374151;line-height:1.5">Casa Horizonte<br>{!! nl2br(e(config('hotel.address'))) !!}</p><a href="{{ config('hotel.maps_url') }}" style="color:#2563eb;font-size:13px;font-weight:bold;text-decoration:none">📍 Ver ubicación en Google Maps →</a></div></td></tr>
<tr><td style="padding:0 30px 30px;text-align:center"><h2 style="margin:0 0 8px;font-size:17px;color:#111827">Síguenos en nuestras redes</h2><p style="margin:0 0 18px;font-size:13px;color:#9ca3af">Conoce nuestras instalaciones, promociones y novedades.</p><a href="{{ config('hotel.facebook') }}" style="display:inline-block;margin:0 5px;width:40px;height:40px;line-height:40px;background:#1877F2;color:#fff;border-radius:50%;text-decoration:none;font-weight:bold;font-size:18px">f</a><a href="{{ config('hotel.instagram') }}" style="display:inline-block;margin:0 5px;width:40px;height:40px;line-height:40px;background:#E1306C;color:#fff;border-radius:50%;text-decoration:none;font-weight:bold;font-size:18px">◎</a><a href="{{ config('hotel.tiktok') }}" style="display:inline-block;margin:0 5px;width:40px;height:40px;line-height:40px;background:#111;color:#fff;border-radius:50%;text-decoration:none;font-weight:bold;font-size:18px">♪</a></td></tr>
<tr><td style="padding:0 30px"><div style="border-top:1px solid #e5e7eb"></div></td></tr><tr><td style="padding:25px 30px 30px;text-align:center"><div style="font-size:15px;color:#374151;line-height:1.6"><strong>¡Estamos deseando recibirte! 🏨</strong></div><p style="margin:8px 0 0;font-size:13px;color:#9ca3af;line-height:1.5">Gracias por elegir Casa Horizonte. Esperamos que disfrutes de una estancia cómoda, tranquila y agradable.</p><a href="{{ $verifyUrl }}" style="display:inline-block;margin-top:18px;background:#2563eb;color:#fff;text-decoration:none;padding:13px 22px;border-radius:7px;font-weight:bold">Ver y verificar mi reserva</a></td></tr><tr><td style="background:#111827;padding:25px 30px;text-align:center"><div style="font-size:17px;font-weight:bold;color:#fff">CASA HORIZONTE</div><div style="margin-top:7px;font-size:12px;color:#9ca3af">Hospedaje • Confort • Tranquilidad</div><div style="margin-top:15px;font-size:11px;color:#6b7280;line-height:1.5">Este correo fue generado automáticamente.<br>Por favor, no respondas directamente a este mensaje.</div></td></tr></table></td></tr></table></body></html>